/**
 * Reapplies hardening that `cap sync` overwrites.
 *
 * Capacitor regenerates parts of the Android project from its own templates, and
 * those templates ship the permissive defaults: a wildcard Cordova whitelist and
 * a FileProvider scoped to whole storage roots. Doing this by hand after every
 * sync is a rule that survives exactly as long as someone remembers it, so the
 * android:sync script runs this instead.
 *
 * Each rule is idempotent and reports whether it changed anything.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const at = (rel) => fileURLToPath(new URL(rel, import.meta.url));

const RULES = [
  {
    file: '../apps/game/android/app/src/main/res/xml/config.xml',
    reason: 'Cordova whitelist regenerates as <access origin="*" />',
    content: `<?xml version='1.0' encoding='utf-8'?>
<!--
  Cordova compatibility shim, present because Capacitor generates it.

  The template ships the whitelist wide open. No Cordova plugin is installed and
  nothing reads this file today, but a wildcard in the tree is the kind of thing
  that quietly becomes load bearing later.

  Regenerated by \`cap sync\`; restored by scripts/harden-android.mjs. Tracked in
  git against Capacitor's own .gitignore so a drift shows up as a diff.
-->
<widget version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <access origin="https://fuse-api.workers.dev" />
</widget>
`,
  },
  {
    file: '../apps/game/android/app/src/main/res/xml/file_paths.xml',
    reason: 'FileProvider regenerates scoped to whole storage roots',
    content: `<?xml version="1.0" encoding="utf-8"?>
<!--
  Scoped to one directory instead of the external-storage and cache roots.

  The generated default is path="." on both, which grants any app holding a
  shared URI read access across everything the app can see there. The only file
  Fuse ever shares is an exported clip.

  Restored by scripts/harden-android.mjs after \`cap sync\`.
-->
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <cache-path name="shared_clips" path="shared/" />
</paths>
`,
  },
];

let changed = 0;
for (const rule of RULES) {
  const path = at(rule.file);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current === rule.content) {
    console.log(`  ok       ${rule.file.replace('../', '')}`);
    continue;
  }
  writeFileSync(path, rule.content);
  changed++;
  console.log(`  restored ${rule.file.replace('../', '')}  (${rule.reason})`);
}

// The manifest is edited rather than replaced: Capacitor owns most of it.
const manifestPath = at('../apps/game/android/app/src/main/AndroidManifest.xml');
let manifest = readFileSync(manifestPath, 'utf8');
if (manifest.includes('android:allowBackup="true"')) {
  manifest = manifest.replace('android:allowBackup="true"', 'android:allowBackup="false"');
  writeFileSync(manifestPath, manifest);
  changed++;
  console.log('  restored AndroidManifest.xml  (allowBackup regenerated as true)');
} else {
  console.log('  ok       AndroidManifest.xml');
}

console.log(changed === 0 ? '\nAndroid hardening intact.' : `\nReapplied ${changed} hardening rule(s).`);
